name: "default-svc-cluster-local-network"

version: 1.4.3

client:

  organization: enspy

  logging:
    level: info
  
  cryptoconfig:
    path: /home/hebo/Projects/doc-checker-hyperledger/crypto-config
  
  credentialStore:
    path: /tmp/default-svc-cluster-local-store
  
    cryptoStore:
      path: /tmp/default-svc-cluster-local-msp
    
  BCCSP:
    security:
      enabled: true
      default:
        provider: "SW"
      hashAlgorithm: "SHA2"
      softVerify: true
      level: 256
  
  tlsCerts:
    systemCertPool: true

channels:

  mainchannel:

    peers:
      peer0-enspy-service:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
  
    policies:
      queryChannelConfig:
        minResponses: 1
        maxTargets: 1
        retryOpts:
          attempts: 5
          initialBackoff: 1000ms
          maxBackoff: 10s
          backoffFactor: 2.0

organizations:
  enspy:
    mspid: enspy
    cryptopath: peerOrganizations/enspy/users/Admin@enspy/msp
    peers:
      - peer0-enspy-service
      - peer1-enspy-service
  enspd:
    mspid: enspd
    cryptopath: peerOrganizations/enspd/users/Admin@enspd/msp
    peers:
      - peer0-enspd-service
      - peer1-enspd-service

orderers:
  _default:
    grpcOptions:
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
  
  orderer0-service:
    grpcOptions:
      ssl-target-name-override: orderer0-service
      grpc-max-send-message-length: 15
    
    tlsCACerts:
      path: /home/fusion/Projects/blockchain/hyperledger-fabric-kubernetes/s5-connecting-everything/crypto-config/ordererOrganizations/default.svc.cluster.local/msp/tlscacerts/ca-root-7054.pem

  
  orderer1-service:
    grpcOptions:
      ssl-target-name-override: orderer1-service
      grpc-max-send-message-length: 15
    
    tlsCACerts:
      path: /home/fusion/Projects/blockchain/hyperledger-fabric-kubernetes/s5-connecting-everything/crypto-config/ordererOrganizations/default.svc.cluster.local/msp/tlscacerts/ca-root-7054.pem

  
  orderer2-service:
    grpcOptions:
      ssl-target-name-override: orderer2-service
      grpc-max-send-message-length: 15
    
    tlsCACerts:
      path: /home/fusion/Projects/blockchain/hyperledger-fabric-kubernetes/s5-connecting-everything/crypto-config/ordererOrganizations/default.svc.cluster.local/msp/tlscacerts/ca-root-7054.pem

peers:

  _default:
    grpcOptions:
      keep-alive-time: 1s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    
  peer0-enspy-service:
    grpcOptions:
      ssl-target-name-override: peer0-enspy-service
      grpc.http2.keepalive_time: 15
    
    tlsCACerts:
      path: /home/fusion/Projects/blockchain/hyperledger-fabric-kubernetes/s5-connecting-everything/crypto-config/peerOrganizations/enspy/msp/tlscacerts/ca-root-7054.pem

  peer1-enspy-service:
    grpcOptions:
      ssl-target-name-override: peer1-enspy-service
      grpc.http2.keepalive_time: 15
    
    tlsCACerts:
      path: /home/fusion/Projects/blockchain/hyperledger-fabric-kubernetes/s5-connecting-everything/crypto-config/peerOrganizations/enspy/msp/tlscacerts/ca-root-7054.pem

    
  peer0-enspd-service:
    grpcOptions:
      ssl-target-name-override: peer0-enspd-service
      grpc.http2.keepalive_time: 15
    
    tlsCACerts:
      path: /home/fusion/Projects/blockchain/hyperledger-fabric-kubernetes/s5-connecting-everything/crypto-config/peerOrganizations/enspd/msp/tlscacerts/ca-root-7054.pem

  peer1-enspd-service:
    grpcOptions:
      ssl-target-name-override: peer1-enspd-service
      grpc.http2.keepalive_time: 15
    
    tlsCACerts:
      path: /home/fusion/Projects/blockchain/hyperledger-fabric-kubernetes/s5-connecting-everything/crypto-config/peerOrganizations/enspd/msp/tlscacerts/ca-root-7054.pem

entityMatchers:

  peer:
    - pattern: (\w*)peer0-enspy-service(\w*)
      urlSubstitutionExp: localhost:7051
      sslTargetOverrideUrlSubstitutionExp: peer0-enspy-service
      mappedHost: peer0-enspy-service

    - pattern: (\w*)peer1-enspy-service(\w*)
      urlSubstitutionExp: localhost:8051
      sslTargetOverrideUrlSubstitutionExp: peer1-enspy-service
      mappedHost: peer1-enspy-service

    - pattern: (\w*)peer0-enspd-service(\w*)
      urlSubstitutionExp: localhost:9051
      sslTargetOverrideUrlSubstitutionExp: peer0-enspd-service
      mappedHost: peer0-enspd-service

    - pattern: (\w*)peer1-enspd-service(\w*)
      urlSubstitutionExp: localhost:10051
      sslTargetOverrideUrlSubstitutionExp: peer1-enspd-service
      mappedHost: peer1-enspd-service

  orderer:
    - pattern: (\w*)orderer0-service(\w*)
      urlSubstitutionExp: localhost:7050
      sslTargetOverrideUrlSubstitutionExp: orderer0-service
      mappedHost: orderer0-service

    - pattern: (\w*)orderer1-service(\w*)
      urlSubstitutionExp: localhost:8050
      sslTargetOverrideUrlSubstitutionExp: orderer1-service
      mappedHost: orderer1-service
      
    - pattern: (\w*)orderer2-service(\w*)
      urlSubstitutionExp: localhost:9050
      sslTargetOverrideUrlSubstitutionExp: orderer2-service
      mappedHost: orderer2-service
