apiVersion: v1
kind: Service
metadata:
  name: enspy-ca-service
  labels: {
    component: enspy,
    type: ca
  }
spec:
  type: ClusterIP
  selector:
    component: enspy
    type: ca
  ports:
    - port: 7054
      targetPort: 7054
