apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli-peer1-enspd-deployment
  labels: {
    component: peer1,
    type: cli,
    org: enspd
  }
spec:
  replicas: 1
  selector:
    matchLabels:
      component: peer1
      type: cli
      org: enspd
  template:
    metadata:
      labels:
        component: peer1
        type: cli
        org: enspd
    spec:
      volumes:
        - name: my-pv-storage
          persistentVolumeClaim:
            claimName: my-pv-claim
      containers:
        - name: peer1-enspd
          image: hyperledger/fabric-tools:2.4
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
          command: ["sleep"]
          args: ["infinity"]
          env:
            - name: GOPATH
              value: /opt/gopath
            - name: CORE_PEER_ADDRESSAUTODETECT
              value: "true"
            - name: CORE_PEER_ID
              value: cli-peer1-enspd
            - name: CORE_PEER_ADDRESS
              value: peer1-enspd-service:7051
            - name: CORE_PEER_LOCALMSPID
              value: enspd
            - name: CORE_PEER_MSPCONFIGPATH
              value: /etc/hyperledger/fabric/msp/users/Admin@enspd/msp
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_CERT_FILE
              value: /etc/hyperledger/fabric/tls/server.crt
            - name: CORE_PEER_TLS_KEY_FILE
              value: /etc/hyperledger/fabric/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /etc/hyperledger/fabric/tls/ca.crt
          volumeMounts:
            - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/orderer
              name: my-pv-storage
              subPath: files/orderer
            - mountPath: /opt/gopath/src/beneficiary
              name: my-pv-storage
              subPath: files/chaincode/beneficiary
            - mountPath: /opt/gopath/src/document_save
              name: my-pv-storage
              subPath: files/chaincode/document_save
            - mountPath: /opt/gopath/src/organization
              name: my-pv-storage
              subPath: files/chaincode/organization
            - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channels
              name: my-pv-storage
              subPath: files/channels
            - mountPath: /etc/hyperledger/fabric/msp
              name: my-pv-storage
              subPath: files/crypto-config/peerOrganizations/enspd
            - mountPath: /etc/hyperledger/fabric/tls
              name: my-pv-storage
              subPath: files/crypto-config/peerOrganizations/enspd/peers/peer1-enspd/tls
            - mountPath: /etc/hyperledger/orderers
              name: my-pv-storage
              subPath: files/crypto-config/ordererOrganizations/orderer
